/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "diags.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(diags_DiagnosticsRequest, diags_DiagnosticsRequest, AUTO)


PB_BIND(diags_DiagnosticsResponse, diags_DiagnosticsResponse, AUTO)


PB_BIND(diags_DiagnosticsResponse_Source, diags_DiagnosticsResponse_Source, AUTO)



