/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_DIAGS_DIAGS_PB_H_INCLUDED
#define PB_DIAGS_DIAGS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _diags_DiagnosticsRequest { 
    pb_callback_t ids; 
} diags_DiagnosticsRequest;

typedef struct _diags_DiagnosticsResponse { 
    pb_callback_t source; 
} diags_DiagnosticsResponse;

typedef PB_BYTES_ARRAY_T(16) diags_DiagnosticsResponse_Source_data_t;
typedef struct _diags_DiagnosticsResponse_Source { 
    bool has_id;
    uint32_t id; 
    bool has_data;
    diags_DiagnosticsResponse_Source_data_t data; 
} diags_DiagnosticsResponse_Source;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define diags_DiagnosticsRequest_init_default    {{{NULL}, NULL}}
#define diags_DiagnosticsResponse_init_default   {{{NULL}, NULL}}
#define diags_DiagnosticsResponse_Source_init_default {false, 0, false, {0, {0}}}
#define diags_DiagnosticsRequest_init_zero       {{{NULL}, NULL}}
#define diags_DiagnosticsResponse_init_zero      {{{NULL}, NULL}}
#define diags_DiagnosticsResponse_Source_init_zero {false, 0, false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define diags_DiagnosticsRequest_ids_tag         1
#define diags_DiagnosticsResponse_source_tag     1
#define diags_DiagnosticsResponse_Source_id_tag  1
#define diags_DiagnosticsResponse_Source_data_tag 2

/* Struct field encoding specification for nanopb */
#define diags_DiagnosticsRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   ids,               1)
#define diags_DiagnosticsRequest_CALLBACK pb_default_field_callback
#define diags_DiagnosticsRequest_DEFAULT NULL

#define diags_DiagnosticsResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  source,            1)
#define diags_DiagnosticsResponse_CALLBACK pb_default_field_callback
#define diags_DiagnosticsResponse_DEFAULT NULL
#define diags_DiagnosticsResponse_source_MSGTYPE diags_DiagnosticsResponse_Source

#define diags_DiagnosticsResponse_Source_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, BYTES,    data,              2)
#define diags_DiagnosticsResponse_Source_CALLBACK NULL
#define diags_DiagnosticsResponse_Source_DEFAULT NULL

extern const pb_msgdesc_t diags_DiagnosticsRequest_msg;
extern const pb_msgdesc_t diags_DiagnosticsResponse_msg;
extern const pb_msgdesc_t diags_DiagnosticsResponse_Source_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define diags_DiagnosticsRequest_fields &diags_DiagnosticsRequest_msg
#define diags_DiagnosticsResponse_fields &diags_DiagnosticsResponse_msg
#define diags_DiagnosticsResponse_Source_fields &diags_DiagnosticsResponse_Source_msg

/* Maximum encoded size of messages (where known) */
/* diags_DiagnosticsRequest_size depends on runtime parameters */
/* diags_DiagnosticsResponse_size depends on runtime parameters */
#define diags_DiagnosticsResponse_Source_size    24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
