APP_PATH = $(MODULE_PATH)/$(USRSRC)

INCLUDE_DIRS += $(BOOST_ROOT)
INCLUDE_DIRS += $(PROJECT_ROOT)/third_party/mqtt_cpp/include
INCLUDE_DIRS += $(PROJECT_ROOT)/proto_defs/src
INCLUDE_DIRS += $(APP_PATH)/protocol
INCLUDE_DIRS += $(APP_PATH)/lorawan

CPPFLAGS += -DMQTT_USE_TLS -DMQTT_STD_STRING_VIEW -DMQTT_STD_OPTIONAL
